---
postgres_version: 15
postgres_port: 5432
postgres_data_dir: /var/lib/postgresql/15/main
postgres_max_connections: 200
postgres_shared_buffers: 256MB

backup_enabled: true
backup_dir: /backup/postgres
backup_retention_days: 7

replication_enabled: true
replication_user: replicator
