---
nginx_port: 80
nginx_user: www-data
nginx_worker_processes: auto
nginx_worker_connections: 1024

app_name: nodejs-api
app_port: 3000
app_env: production

docker_image: deverathore13/node-api:latest
docker_network: app-network

ssl_enabled: true
ssl_cert_path: /etc/nginx/ssl/cert.pem
ssl_key_path: /etc/nginx/ssl/key.pem
